apiVersion: apps/v1
kind: Deployment
metadata:
  name: airports
  labels:
    app: airports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airports
  template:
    metadata:
      labels:
        app: airports
    spec:
      containers:
      - name: airports
        image: airports:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
