apiVersion: apps/v1
kind: Deployment
metadata:
  name: Applicaion_Name
  labels:
    app: Applicaion_Name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Applicaion_Name
  template:
    metadata:
      labels:
        app: Applicaion_Name
    spec:
      containers:
      - name: Applicaion_Name
        image: Applicaion_Name:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
