apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: airports
  labels:
    app.kubernetes.io/name: airports
    app.kubernetes.io/version: 1.16.0
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  rules:
    - host: pb.info.co
      http:
        paths: 
          - path: /countries
            backend:
              serviceName: countries
              servicePort: 8080        
          - path: /airports
            backend:
              serviceName: airports
              servicePort: 8080      
