apiVersion: v1
kind: Service
metadata:
  name: Applicaion_Name
  labels:
    run: Applicaion_Name
spec:
  type: CluserIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: Applicaion_Name
