apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    run: ${APP_NAME}
spec:
  type: CluserIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: ${APP_NAME}
